# Generated by Django 3.2 on 2021-09-20 04:43

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(max_length=1023, null=True)),
                ('secret_description', models.TextField(max_length=1023, null=True)),
                ('price', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('CVE', 'CVE'), ('KGS', 'KGS'), ('CNX', 'CNX'), ('TRY', 'TRY'), ('XAG', 'XAG'), ('LVL', 'LVL'), ('BYN', 'BYN'), ('MNT', 'MNT'), ('MUR', 'MUR'), ('VNN', 'VNN'), ('ZMW', 'ZMW'), ('ZRZ', 'ZRZ'), ('MYR', 'MYR'), ('KWD', 'KWD'), ('LUC', 'LUC'), ('UYW', 'UYW'), ('CLF', 'CLF'), ('ESP', 'ESP'), ('UZS', 'UZS'), ('BYR', 'BYR'), ('DJF', 'DJF'), ('XEU', 'XEU'), ('ESA', 'ESA'), ('GQE', 'GQE'), ('SCR', 'SCR'), ('TMM', 'TMM'), ('MMK', 'MMK'), ('EUR', 'EUR'), ('PGK', 'PGK'), ('YUM', 'YUM'), ('XAU', 'XAU'), ('USS', 'USS'), ('LBP', 'LBP'), ('AMD', 'AMD'), ('BOP', 'BOP'), ('COP', 'COP'), ('XBB', 'XBB'), ('KZT', 'KZT'), ('CAD', 'CAD'), ('RSD', 'RSD'), ('SEK', 'SEK'), ('MAF', 'MAF'), ('MZE', 'MZE'), ('BND', 'BND'), ('GEL', 'GEL'), ('BRZ', 'BRZ'), ('SRD', 'SRD'), ('SHP', 'SHP'), ('GWE', 'GWE'), ('GMD', 'GMD'), ('ROL', 'ROL'), ('CSD', 'CSD'), ('IDR', 'IDR'), ('BRL', 'BRL'), ('LRD', 'LRD'), ('TMT', 'TMT'), ('MZN', 'MZN'), ('BEL', 'BEL'), ('MAD', 'MAD'), ('GIP', 'GIP'), ('CDF', 'CDF'), ('KMF', 'KMF'), ('ZWR', 'ZWR'), ('AOA', 'AOA'), ('YER', 'YER'), ('PEN', 'PEN'), ('AOK', 'AOK'), ('SDD', 'SDD'), ('AFN', 'AFN'), ('ISJ', 'ISJ'), ('USN', 'USN'), ('EGP', 'EGP'), ('DEM', 'DEM'), ('XSU', 'XSU'), ('IQD', 'IQD'), ('XPF', 'XPF'), ('VES', 'VES'), ('BEF', 'BEF'), ('BOB', 'BOB'), ('XPD', 'XPD'), ('CLE', 'CLE'), ('ATS', 'ATS'), ('MXV', 'MXV'), ('TJS', 'TJS'), ('SDP', 'SDP'), ('TND', 'TND'), ('SDG', 'SDG'), ('NIO', 'NIO'), ('PYG', 'PYG'), ('HKD', 'HKD'), ('SVC', 'SVC'), ('ALL', 'ALL'), ('UYU', 'UYU'), ('KES', 'KES'), ('SYP', 'SYP'), ('BRC', 'BRC'), ('ANG', 'ANG'), ('MKD', 'MKD'), ('IRR', 'IRR'), ('FRF', 'FRF'), ('CNH', 'CNH'), ('MXP', 'MXP'), ('THB', 'THB'), ('CSK', 'CSK'), ('ARM', 'ARM'), ('KRO', 'KRO'), ('PAB', 'PAB'), ('BOL', 'BOL'), ('BRN', 'BRN'), ('TOP', 'TOP'), ('UYP', 'UYP'), ('HRK', 'HRK'), ('BRR', 'BRR'), ('STN', 'STN'), ('MDC', 'MDC'), ('SOS', 'SOS'), ('VEB', 'VEB'), ('BEC', 'BEC'), ('CHE', 'CHE'), ('SIT', 'SIT'), ('VUV', 'VUV'), ('WST', 'WST'), ('MTL', 'MTL'), ('CUC', 'CUC'), ('IEP', 'IEP'), ('ARP', 'ARP'), ('BAN', 'BAN'), ('LTL', 'LTL'), ('RWF', 'RWF'), ('ZRN', 'ZRN'), ('LVR', 'LVR'), ('FJD', 'FJD'), ('CYP', 'CYP'), ('LUF', 'LUF'), ('PEI', 'PEI'), ('SRG', 'SRG'), ('MZM', 'MZM'), ('GNS', 'GNS'), ('BGM', 'BGM'), ('RUR', 'RUR'), ('ESB', 'ESB'), ('MWK', 'MWK'), ('PLN', 'PLN'), ('GTQ', 'GTQ'), ('ARL', 'ARL'), ('MRU', 'MRU'), ('PTE', 'PTE'), ('PES', 'PES'), ('BIF', 'BIF'), ('BDT', 'BDT'), ('HTG', 'HTG'), ('MGF', 'MGF'), ('STD', 'STD'), ('UGX', 'UGX'), ('ZWD', 'ZWD'), ('BYB', 'BYB'), ('VND', 'VND'), ('AON', 'AON'), ('DKK', 'DKK'), ('SLL', 'SLL'), ('BGO', 'BGO'), ('MDL', 'MDL'), ('AOR', 'AOR'), ('GBP', 'GBP'), ('TTD', 'TTD'), ('ADP', 'ADP'), ('HRD', 'HRD'), ('SBD', 'SBD'), ('YUN', 'YUN'), ('DZD', 'DZD'), ('GHS', 'GHS'), ('EEK', 'EEK'), ('JMD', 'JMD'), ('NGN', 'NGN'), ('YDD', 'YDD'), ('MVP', 'MVP'), ('UAK', 'UAK'), ('LSL', 'LSL'), ('KRW', 'KRW'), ('XBA', 'XBA'), ('ARA', 'ARA'), ('GNF', 'GNF'), ('GEK', 'GEK'), ('SZL', 'SZL'), ('NPR', 'NPR'), ('ARS', 'ARS'), ('SKK', 'SKK'), ('FKP', 'FKP'), ('BMD', 'BMD'), ('GRD', 'GRD'), ('LUL', 'LUL'), ('BUK', 'BUK'), ('PLZ', 'PLZ'), ('XPT', 'XPT'), ('ALK', 'ALK'), ('BRE', 'BRE'), ('LYD', 'LYD'), ('SUR', 'SUR'), ('AZM', 'AZM'), ('COU', 'COU'), ('ILS', 'ILS'), ('XAF', 'XAF'), ('XUA', 'XUA'), ('UAH', 'UAH'), ('LKR', 'LKR'), ('CHF', 'CHF'), ('CHW', 'CHW'), ('XCD', 'XCD'), ('TWD', 'TWD'), ('MGA', 'MGA'), ('BTN', 'BTN'), ('HNL', 'HNL'), ('KRH', 'KRH'), ('KHR', 'KHR'), ('ZAR', 'ZAR'), ('MXN', 'MXN'), ('INR', 'INR'), ('CRC', 'CRC'), ('USD', 'USD'), ('SGD', 'SGD'), ('ILR', 'ILR'), ('JPY', 'JPY'), ('BWP', 'BWP'), ('AFA', 'AFA'), ('BHD', 'BHD'), ('LAK', 'LAK'), ('RUB', 'RUB'), ('XRE', 'XRE'), ('YUR', 'YUR'), ('CLP', 'CLP'), ('LTT', 'LTT'), ('AWG', 'AWG'), ('MCF', 'MCF'), ('AZN', 'AZN'), ('PKR', 'PKR'), ('BOV', 'BOV'), ('MVR', 'MVR'), ('NIC', 'NIC'), ('RON', 'RON'), ('RHD', 'RHD'), ('NAD', 'NAD'), ('ETB', 'ETB'), ('MRO', 'MRO'), ('BAM', 'BAM'), ('XFU', 'XFU'), ('BSD', 'BSD'), ('ITL', 'ITL'), ('BGN', 'BGN'), ('HUF', 'HUF'), ('ECS', 'ECS'), ('DDM', 'DDM'), ('FIM', 'FIM'), ('AED', 'AED'), ('MLF', 'MLF'), ('ZAL', 'ZAL'), ('TPE', 'TPE'), ('TRL', 'TRL'), ('DOP', 'DOP'), ('TJR', 'TJR'), ('NLG', 'NLG'), ('GHC', 'GHC'), ('ERN', 'ERN'), ('XBD', 'XBD'), ('XDR', 'XDR'), ('TZS', 'TZS'), ('CNY', 'CNY'), ('QAR', 'QAR'), ('SAR', 'SAR'), ('KYD', 'KYD'), ('XFO', 'XFO'), ('GWP', 'GWP'), ('ILP', 'ILP'), ('NZD', 'NZD'), ('ECV', 'ECV'), ('MOP', 'MOP'), ('AUD', 'AUD'), ('MKN', 'MKN'), ('CZK', 'CZK'), ('PHP', 'PHP'), ('XOF', 'XOF'), ('YUD', 'YUD'), ('ZWL', 'ZWL'), ('BGL', 'BGL'), ('BAD', 'BAD'), ('UGS', 'UGS'), ('VEF', 'VEF'), ('BZD', 'BZD'), ('UYI', 'UYI'), ('BRB', 'BRB'), ('CUP', 'CUP'), ('MTP', 'MTP'), ('ISK', 'ISK'), ('GYD', 'GYD'), ('JOD', 'JOD'), ('SSP', 'SSP'), ('ZMK', 'ZMK'), ('OMR', 'OMR'), ('XXX', 'XXX'), ('BBD', 'BBD'), ('KPW', 'KPW'), ('NOK', 'NOK'), ('XBC', 'XBC'), ('XTS', 'XTS')], default='USD', max_length=3)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=65)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('i', 'Initiated'), ('c', 'Completed'), ('r', 'Rejected')], default='p', max_length=1)),
                ('txid', models.TextField(null=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawls', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status_of_transaction', models.IntegerField(choices=[(-1, 'Not Started'), (0, 'Unconfirmed'), (1, 'Partial Confirmed'), (2, 'Confirmed')], default=-1)),
                ('expected_value', models.DecimalField(decimal_places=10, max_digits=65, null=True)),
                ('usd_price', models.DecimalField(decimal_places=10, max_digits=65, null=True)),
                ('received_value', models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True)),
                ('txid', models.TextField(null=True)),
                ('address', models.TextField(null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('is_payment_complete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_data', models.BinaryField()),
                ('file_name', models.TextField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.product')),
            ],
        ),
    ]
