# Generated by Django 3.2 on 2021-09-20 05:06

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(max_length=1023, null=True)),
                ('secret_description', models.TextField(max_length=1023, null=True)),
                ('price', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('YUD', 'YUD'), ('MDC', 'MDC'), ('IRR', 'IRR'), ('BOV', 'BOV'), ('SOS', 'SOS'), ('KPW', 'KPW'), ('RUR', 'RUR'), ('SIT', 'SIT'), ('SKK', 'SKK'), ('BTN', 'BTN'), ('JOD', 'JOD'), ('UAK', 'UAK'), ('SUR', 'SUR'), ('LAK', 'LAK'), ('CLF', 'CLF'), ('LTT', 'LTT'), ('RSD', 'RSD'), ('ZMK', 'ZMK'), ('UYP', 'UYP'), ('XEU', 'XEU'), ('BRC', 'BRC'), ('GBP', 'GBP'), ('AZN', 'AZN'), ('PLN', 'PLN'), ('NZD', 'NZD'), ('MTP', 'MTP'), ('MKD', 'MKD'), ('MNT', 'MNT'), ('EGP', 'EGP'), ('YUN', 'YUN'), ('USD', 'USD'), ('MAD', 'MAD'), ('BEF', 'BEF'), ('XAU', 'XAU'), ('KHR', 'KHR'), ('SBD', 'SBD'), ('TOP', 'TOP'), ('UAH', 'UAH'), ('MYR', 'MYR'), ('BZD', 'BZD'), ('ECS', 'ECS'), ('XFU', 'XFU'), ('SSP', 'SSP'), ('WST', 'WST'), ('BOL', 'BOL'), ('MZE', 'MZE'), ('KGS', 'KGS'), ('ROL', 'ROL'), ('YDD', 'YDD'), ('MLF', 'MLF'), ('BRN', 'BRN'), ('BGM', 'BGM'), ('LRD', 'LRD'), ('XBB', 'XBB'), ('COP', 'COP'), ('XPT', 'XPT'), ('CRC', 'CRC'), ('STD', 'STD'), ('FRF', 'FRF'), ('CUP', 'CUP'), ('ZRZ', 'ZRZ'), ('SDP', 'SDP'), ('OMR', 'OMR'), ('MGA', 'MGA'), ('SEK', 'SEK'), ('BSD', 'BSD'), ('ESB', 'ESB'), ('IQD', 'IQD'), ('LUF', 'LUF'), ('MVP', 'MVP'), ('XFO', 'XFO'), ('ZAL', 'ZAL'), ('GNS', 'GNS'), ('TRY', 'TRY'), ('BIF', 'BIF'), ('JPY', 'JPY'), ('HTG', 'HTG'), ('ETB', 'ETB'), ('UGS', 'UGS'), ('ESA', 'ESA'), ('BND', 'BND'), ('TTD', 'TTD'), ('XDR', 'XDR'), ('MRO', 'MRO'), ('CNH', 'CNH'), ('LUC', 'LUC'), ('BUK', 'BUK'), ('BAD', 'BAD'), ('LTL', 'LTL'), ('NIC', 'NIC'), ('CLP', 'CLP'), ('CDF', 'CDF'), ('ZWL', 'ZWL'), ('ITL', 'ITL'), ('JMD', 'JMD'), ('KES', 'KES'), ('GEL', 'GEL'), ('BEL', 'BEL'), ('BGN', 'BGN'), ('ARP', 'ARP'), ('BGL', 'BGL'), ('XAF', 'XAF'), ('XPF', 'XPF'), ('AON', 'AON'), ('VUV', 'VUV'), ('GEK', 'GEK'), ('MAF', 'MAF'), ('ZMW', 'ZMW'), ('YUR', 'YUR'), ('TND', 'TND'), ('CVE', 'CVE'), ('MRU', 'MRU'), ('KRH', 'KRH'), ('SZL', 'SZL'), ('TZS', 'TZS'), ('NLG', 'NLG'), ('PEI', 'PEI'), ('MGF', 'MGF'), ('PES', 'PES'), ('XTS', 'XTS'), ('BRL', 'BRL'), ('HRK', 'HRK'), ('MOP', 'MOP'), ('LKR', 'LKR'), ('LVL', 'LVL'), ('BMD', 'BMD'), ('NOK', 'NOK'), ('EEK', 'EEK'), ('HKD', 'HKD'), ('UYW', 'UYW'), ('BYN', 'BYN'), ('BOB', 'BOB'), ('NGN', 'NGN'), ('IDR', 'IDR'), ('LBP', 'LBP'), ('THB', 'THB'), ('BRR', 'BRR'), ('SDD', 'SDD'), ('PTE', 'PTE'), ('MMK', 'MMK'), ('XBA', 'XBA'), ('AFN', 'AFN'), ('CYP', 'CYP'), ('FIM', 'FIM'), ('BAN', 'BAN'), ('IEP', 'IEP'), ('SRD', 'SRD'), ('ZWR', 'ZWR'), ('ESP', 'ESP'), ('GTQ', 'GTQ'), ('QAR', 'QAR'), ('ADP', 'ADP'), ('ATS', 'ATS'), ('BEC', 'BEC'), ('MXP', 'MXP'), ('XUA', 'XUA'), ('XAG', 'XAG'), ('ARL', 'ARL'), ('XRE', 'XRE'), ('KWD', 'KWD'), ('AZM', 'AZM'), ('ZAR', 'ZAR'), ('TMT', 'TMT'), ('SDG', 'SDG'), ('VEB', 'VEB'), ('ALK', 'ALK'), ('BOP', 'BOP'), ('HUF', 'HUF'), ('CUC', 'CUC'), ('UZS', 'UZS'), ('USN', 'USN'), ('CSK', 'CSK'), ('SCR', 'SCR'), ('DJF', 'DJF'), ('CAD', 'CAD'), ('ARS', 'ARS'), ('ERN', 'ERN'), ('ARM', 'ARM'), ('GHS', 'GHS'), ('USS', 'USS'), ('LVR', 'LVR'), ('CHE', 'CHE'), ('PAB', 'PAB'), ('DOP', 'DOP'), ('HRD', 'HRD'), ('INR', 'INR'), ('RWF', 'RWF'), ('BHD', 'BHD'), ('CSD', 'CSD'), ('MCF', 'MCF'), ('PLZ', 'PLZ'), ('XPD', 'XPD'), ('SHP', 'SHP'), ('MTL', 'MTL'), ('NIO', 'NIO'), ('MDL', 'MDL'), ('AMD', 'AMD'), ('AOK', 'AOK'), ('CLE', 'CLE'), ('RHD', 'RHD'), ('YER', 'YER'), ('MKN', 'MKN'), ('SGD', 'SGD'), ('GNF', 'GNF'), ('SYP', 'SYP'), ('DDM', 'DDM'), ('PYG', 'PYG'), ('BAM', 'BAM'), ('KZT', 'KZT'), ('GMD', 'GMD'), ('AOA', 'AOA'), ('VES', 'VES'), ('ILR', 'ILR'), ('NPR', 'NPR'), ('BDT', 'BDT'), ('RON', 'RON'), ('NAD', 'NAD'), ('DZD', 'DZD'), ('VND', 'VND'), ('XBD', 'XBD'), ('AUD', 'AUD'), ('MVR', 'MVR'), ('UYU', 'UYU'), ('KYD', 'KYD'), ('DEM', 'DEM'), ('ECV', 'ECV'), ('ZRN', 'ZRN'), ('XSU', 'XSU'), ('PHP', 'PHP'), ('UGX', 'UGX'), ('CZK', 'CZK'), ('XXX', 'XXX'), ('MUR', 'MUR'), ('ISJ', 'ISJ'), ('BYR', 'BYR'), ('TJR', 'TJR'), ('CNY', 'CNY'), ('AFA', 'AFA'), ('PGK', 'PGK'), ('BRZ', 'BRZ'), ('ZWD', 'ZWD'), ('BBD', 'BBD'), ('HNL', 'HNL'), ('MZM', 'MZM'), ('SLL', 'SLL'), ('TRL', 'TRL'), ('EUR', 'EUR'), ('CHW', 'CHW'), ('GIP', 'GIP'), ('FKP', 'FKP'), ('KRW', 'KRW'), ('PEN', 'PEN'), ('YUM', 'YUM'), ('COU', 'COU'), ('GQE', 'GQE'), ('MWK', 'MWK'), ('KMF', 'KMF'), ('BYB', 'BYB'), ('UYI', 'UYI'), ('XBC', 'XBC'), ('MXV', 'MXV'), ('MZN', 'MZN'), ('XCD', 'XCD'), ('LUL', 'LUL'), ('GHC', 'GHC'), ('KRO', 'KRO'), ('ISK', 'ISK'), ('TJS', 'TJS'), ('CNX', 'CNX'), ('GWP', 'GWP'), ('DKK', 'DKK'), ('GWE', 'GWE'), ('BRE', 'BRE'), ('CHF', 'CHF'), ('SAR', 'SAR'), ('GYD', 'GYD'), ('VNN', 'VNN'), ('BRB', 'BRB'), ('AWG', 'AWG'), ('ARA', 'ARA'), ('LYD', 'LYD'), ('AED', 'AED'), ('FJD', 'FJD'), ('STN', 'STN'), ('LSL', 'LSL'), ('PKR', 'PKR'), ('ANG', 'ANG'), ('ILP', 'ILP'), ('TPE', 'TPE'), ('TWD', 'TWD'), ('AOR', 'AOR'), ('MXN', 'MXN'), ('ILS', 'ILS'), ('TMM', 'TMM'), ('VEF', 'VEF'), ('XOF', 'XOF'), ('SVC', 'SVC'), ('ALL', 'ALL'), ('GRD', 'GRD'), ('RUB', 'RUB'), ('SRG', 'SRG'), ('BWP', 'BWP'), ('BGO', 'BGO')], default='USD', max_length=3)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=65)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('i', 'Initiated'), ('c', 'Completed'), ('r', 'Rejected')], default='p', max_length=1)),
                ('txid', models.TextField(null=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawls', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status_of_transaction', models.IntegerField(choices=[(-1, 'Not Started'), (0, 'Unconfirmed'), (1, 'Partial Confirmed'), (2, 'Confirmed')], default=-1)),
                ('expected_value', models.DecimalField(decimal_places=10, max_digits=65, null=True)),
                ('usd_price', models.DecimalField(decimal_places=10, max_digits=65, null=True)),
                ('received_value', models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True)),
                ('txid', models.TextField(null=True)),
                ('address', models.CharField(max_length=100, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('is_payment_complete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_data', models.BinaryField()),
                ('file_name', models.TextField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.product')),
            ],
        ),
    ]
