# Generated by Django 3.2 on 2021-09-20 04:37

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(max_length=1023, null=True)),
                ('secret_description', models.TextField(max_length=1023, null=True)),
                ('price', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('MRU', 'MRU'), ('GHS', 'GHS'), ('ZWL', 'ZWL'), ('TJS', 'TJS'), ('FIM', 'FIM'), ('RWF', 'RWF'), ('CLP', 'CLP'), ('ARP', 'ARP'), ('BWP', 'BWP'), ('UGS', 'UGS'), ('GBP', 'GBP'), ('MZM', 'MZM'), ('CRC', 'CRC'), ('AWG', 'AWG'), ('MXV', 'MXV'), ('BRE', 'BRE'), ('ROL', 'ROL'), ('SDP', 'SDP'), ('INR', 'INR'), ('BYB', 'BYB'), ('COP', 'COP'), ('XUA', 'XUA'), ('UAK', 'UAK'), ('YUM', 'YUM'), ('TND', 'TND'), ('ZMK', 'ZMK'), ('AFA', 'AFA'), ('XBA', 'XBA'), ('BBD', 'BBD'), ('TJR', 'TJR'), ('HRD', 'HRD'), ('LUL', 'LUL'), ('CDF', 'CDF'), ('NLG', 'NLG'), ('MRO', 'MRO'), ('XSU', 'XSU'), ('CSK', 'CSK'), ('GRD', 'GRD'), ('BGM', 'BGM'), ('BGO', 'BGO'), ('LAK', 'LAK'), ('LTL', 'LTL'), ('YER', 'YER'), ('YDD', 'YDD'), ('GEL', 'GEL'), ('ZAR', 'ZAR'), ('BEL', 'BEL'), ('EEK', 'EEK'), ('KYD', 'KYD'), ('GNF', 'GNF'), ('ZWR', 'ZWR'), ('KHR', 'KHR'), ('LKR', 'LKR'), ('ZWD', 'ZWD'), ('TPE', 'TPE'), ('GMD', 'GMD'), ('XRE', 'XRE'), ('BGL', 'BGL'), ('BRB', 'BRB'), ('BMD', 'BMD'), ('BYN', 'BYN'), ('CZK', 'CZK'), ('LRD', 'LRD'), ('AMD', 'AMD'), ('BOB', 'BOB'), ('LYD', 'LYD'), ('SZL', 'SZL'), ('PEI', 'PEI'), ('DEM', 'DEM'), ('XXX', 'XXX'), ('VUV', 'VUV'), ('DOP', 'DOP'), ('DKK', 'DKK'), ('PAB', 'PAB'), ('UYW', 'UYW'), ('WST', 'WST'), ('XAG', 'XAG'), ('CNH', 'CNH'), ('MGF', 'MGF'), ('ZRZ', 'ZRZ'), ('CUP', 'CUP'), ('SIT', 'SIT'), ('AUD', 'AUD'), ('DZD', 'DZD'), ('SGD', 'SGD'), ('IQD', 'IQD'), ('MLF', 'MLF'), ('BSD', 'BSD'), ('SEK', 'SEK'), ('ESB', 'ESB'), ('TWD', 'TWD'), ('ETB', 'ETB'), ('ARM', 'ARM'), ('BUK', 'BUK'), ('LVR', 'LVR'), ('BAN', 'BAN'), ('SHP', 'SHP'), ('VEB', 'VEB'), ('NZD', 'NZD'), ('TRL', 'TRL'), ('KZT', 'KZT'), ('GNS', 'GNS'), ('ISJ', 'ISJ'), ('BRN', 'BRN'), ('UGX', 'UGX'), ('MDL', 'MDL'), ('XBC', 'XBC'), ('RSD', 'RSD'), ('SUR', 'SUR'), ('ESA', 'ESA'), ('MNT', 'MNT'), ('XOF', 'XOF'), ('BEC', 'BEC'), ('CYP', 'CYP'), ('MZE', 'MZE'), ('NIO', 'NIO'), ('SOS', 'SOS'), ('ITL', 'ITL'), ('TRY', 'TRY'), ('JOD', 'JOD'), ('AON', 'AON'), ('ANG', 'ANG'), ('SAR', 'SAR'), ('SLL', 'SLL'), ('CVE', 'CVE'), ('MTP', 'MTP'), ('VEF', 'VEF'), ('SRG', 'SRG'), ('ILR', 'ILR'), ('ILP', 'ILP'), ('NGN', 'NGN'), ('MKD', 'MKD'), ('ZMW', 'ZMW'), ('PGK', 'PGK'), ('TMM', 'TMM'), ('QAR', 'QAR'), ('TOP', 'TOP'), ('ATS', 'ATS'), ('MMK', 'MMK'), ('XPT', 'XPT'), ('CHF', 'CHF'), ('CHW', 'CHW'), ('LSL', 'LSL'), ('MVR', 'MVR'), ('AOA', 'AOA'), ('RUR', 'RUR'), ('AZM', 'AZM'), ('KPW', 'KPW'), ('SVC', 'SVC'), ('XPD', 'XPD'), ('ADP', 'ADP'), ('NOK', 'NOK'), ('GTQ', 'GTQ'), ('IDR', 'IDR'), ('SYP', 'SYP'), ('AOK', 'AOK'), ('EUR', 'EUR'), ('MTL', 'MTL'), ('SDD', 'SDD'), ('IRR', 'IRR'), ('AED', 'AED'), ('JPY', 'JPY'), ('FRF', 'FRF'), ('UZS', 'UZS'), ('HRK', 'HRK'), ('KGS', 'KGS'), ('LTT', 'LTT'), ('SCR', 'SCR'), ('UAH', 'UAH'), ('XBD', 'XBD'), ('HNL', 'HNL'), ('PHP', 'PHP'), ('DJF', 'DJF'), ('ZRN', 'ZRN'), ('AOR', 'AOR'), ('SDG', 'SDG'), ('TZS', 'TZS'), ('BRZ', 'BRZ'), ('SSP', 'SSP'), ('PES', 'PES'), ('LUF', 'LUF'), ('MUR', 'MUR'), ('GWE', 'GWE'), ('ZAL', 'ZAL'), ('BAD', 'BAD'), ('ALL', 'ALL'), ('EGP', 'EGP'), ('MOP', 'MOP'), ('ARL', 'ARL'), ('BTN', 'BTN'), ('PLN', 'PLN'), ('MCF', 'MCF'), ('AFN', 'AFN'), ('HUF', 'HUF'), ('IEP', 'IEP'), ('BZD', 'BZD'), ('GIP', 'GIP'), ('SBD', 'SBD'), ('GYD', 'GYD'), ('GQE', 'GQE'), ('BOP', 'BOP'), ('COU', 'COU'), ('MDC', 'MDC'), ('ISK', 'ISK'), ('YUD', 'YUD'), ('MWK', 'MWK'), ('XDR', 'XDR'), ('UYI', 'UYI'), ('LUC', 'LUC'), ('UYU', 'UYU'), ('ARA', 'ARA'), ('GEK', 'GEK'), ('XPF', 'XPF'), ('LVL', 'LVL'), ('PTE', 'PTE'), ('MXN', 'MXN'), ('NIC', 'NIC'), ('CNY', 'CNY'), ('FKP', 'FKP'), ('MVP', 'MVP'), ('RHD', 'RHD'), ('HKD', 'HKD'), ('THB', 'THB'), ('BHD', 'BHD'), ('BIF', 'BIF'), ('MKN', 'MKN'), ('TMT', 'TMT'), ('KWD', 'KWD'), ('YUN', 'YUN'), ('CUC', 'CUC'), ('CLF', 'CLF'), ('MXP', 'MXP'), ('PEN', 'PEN'), ('KRO', 'KRO'), ('USS', 'USS'), ('OMR', 'OMR'), ('ALK', 'ALK'), ('PYG', 'PYG'), ('VNN', 'VNN'), ('VES', 'VES'), ('KMF', 'KMF'), ('XFO', 'XFO'), ('HTG', 'HTG'), ('BRR', 'BRR'), ('XFU', 'XFU'), ('ARS', 'ARS'), ('BOL', 'BOL'), ('USD', 'USD'), ('GWP', 'GWP'), ('XCD', 'XCD'), ('RUB', 'RUB'), ('CNX', 'CNX'), ('KRW', 'KRW'), ('TTD', 'TTD'), ('XAF', 'XAF'), ('SRD', 'SRD'), ('ESP', 'ESP'), ('MYR', 'MYR'), ('MZN', 'MZN'), ('ILS', 'ILS'), ('BYR', 'BYR'), ('XEU', 'XEU'), ('XTS', 'XTS'), ('PKR', 'PKR'), ('BDT', 'BDT'), ('BEF', 'BEF'), ('LBP', 'LBP'), ('DDM', 'DDM'), ('ECV', 'ECV'), ('GHC', 'GHC'), ('STN', 'STN'), ('XAU', 'XAU'), ('MGA', 'MGA'), ('JMD', 'JMD'), ('UYP', 'UYP'), ('STD', 'STD'), ('PLZ', 'PLZ'), ('XBB', 'XBB'), ('MAD', 'MAD'), ('CHE', 'CHE'), ('NPR', 'NPR'), ('ECS', 'ECS'), ('CAD', 'CAD'), ('BND', 'BND'), ('ERN', 'ERN'), ('BRC', 'BRC'), ('BRL', 'BRL'), ('MAF', 'MAF'), ('USN', 'USN'), ('KRH', 'KRH'), ('AZN', 'AZN'), ('FJD', 'FJD'), ('BGN', 'BGN'), ('BAM', 'BAM'), ('BOV', 'BOV'), ('VND', 'VND'), ('YUR', 'YUR'), ('CSD', 'CSD'), ('RON', 'RON'), ('KES', 'KES'), ('SKK', 'SKK'), ('NAD', 'NAD'), ('CLE', 'CLE')], default='USD', max_length=3)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=100)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('i', 'Initiated'), ('c', 'Completed'), ('r', 'Rejected')], default='p', max_length=1)),
                ('txid', models.TextField(null=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawls', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status_of_transaction', models.IntegerField(choices=[(-1, 'Not Started'), (0, 'Unconfirmed'), (1, 'Partial Confirmed'), (2, 'Confirmed')], default=-1)),
                ('expected_value', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
                ('usd_price', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
                ('received_value', models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True)),
                ('txid', models.TextField(null=True)),
                ('address', models.TextField(null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('crypto', models.CharField(choices=[('BTC', 'Btc'), ('BCH', 'Bch')], max_length=255, null=True)),
                ('is_payment_complete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_data', models.BinaryField()),
                ('file_name', models.TextField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.product')),
            ],
        ),
    ]
