# Generated by Django 3.2 on 2021-09-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_value',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_price',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('QAR', 'QAR'), ('ECV', 'ECV'), ('UAK', 'UAK'), ('COU', 'COU'), ('PEN', 'PEN'), ('ATS', 'ATS'), ('FIM', 'FIM'), ('UYW', 'UYW'), ('STD', 'STD'), ('YUN', 'YUN'), ('ILR', 'ILR'), ('AFN', 'AFN'), ('LRD', 'LRD'), ('PEI', 'PEI'), ('BEL', 'BEL'), ('THB', 'THB'), ('AOA', 'AOA'), ('NZD', 'NZD'), ('CNH', 'CNH'), ('GTQ', 'GTQ'), ('RUB', 'RUB'), ('XUA', 'XUA'), ('VES', 'VES'), ('KRW', 'KRW'), ('JMD', 'JMD'), ('CSK', 'CSK'), ('SCR', 'SCR'), ('XTS', 'XTS'), ('UYP', 'UYP'), ('KMF', 'KMF'), ('NOK', 'NOK'), ('CLF', 'CLF'), ('AWG', 'AWG'), ('MXN', 'MXN'), ('AUD', 'AUD'), ('LVR', 'LVR'), ('ZAR', 'ZAR'), ('VND', 'VND'), ('MZN', 'MZN'), ('NAD', 'NAD'), ('NPR', 'NPR'), ('ILS', 'ILS'), ('AZM', 'AZM'), ('ROL', 'ROL'), ('RHD', 'RHD'), ('DDM', 'DDM'), ('ZWR', 'ZWR'), ('GNF', 'GNF'), ('CNY', 'CNY'), ('UZS', 'UZS'), ('PYG', 'PYG'), ('SDP', 'SDP'), ('VUV', 'VUV'), ('RON', 'RON'), ('YUR', 'YUR'), ('SAR', 'SAR'), ('XFO', 'XFO'), ('AFA', 'AFA'), ('XSU', 'XSU'), ('ALL', 'ALL'), ('NIO', 'NIO'), ('VEB', 'VEB'), ('ADP', 'ADP'), ('BRB', 'BRB'), ('IDR', 'IDR'), ('YER', 'YER'), ('BGN', 'BGN'), ('MLF', 'MLF'), ('KPW', 'KPW'), ('CVE', 'CVE'), ('LKR', 'LKR'), ('LVL', 'LVL'), ('SGD', 'SGD'), ('UYU', 'UYU'), ('CNX', 'CNX'), ('LUL', 'LUL'), ('XAU', 'XAU'), ('MZE', 'MZE'), ('EEK', 'EEK'), ('BRL', 'BRL'), ('LUC', 'LUC'), ('ZRN', 'ZRN'), ('XPF', 'XPF'), ('BOP', 'BOP'), ('DKK', 'DKK'), ('SRD', 'SRD'), ('MWK', 'MWK'), ('CHF', 'CHF'), ('GEK', 'GEK'), ('DJF', 'DJF'), ('BSD', 'BSD'), ('DZD', 'DZD'), ('IQD', 'IQD'), ('BOV', 'BOV'), ('XBB', 'XBB'), ('JPY', 'JPY'), ('XFU', 'XFU'), ('GBP', 'GBP'), ('ESP', 'ESP'), ('MDL', 'MDL'), ('ECS', 'ECS'), ('GEL', 'GEL'), ('KRH', 'KRH'), ('IRR', 'IRR'), ('MDC', 'MDC'), ('SYP', 'SYP'), ('BGL', 'BGL'), ('BAM', 'BAM'), ('MYR', 'MYR'), ('GMD', 'GMD'), ('KRO', 'KRO'), ('SUR', 'SUR'), ('ARM', 'ARM'), ('CSD', 'CSD'), ('SLL', 'SLL'), ('MNT', 'MNT'), ('BYR', 'BYR'), ('BYB', 'BYB'), ('BEF', 'BEF'), ('AED', 'AED'), ('ANG', 'ANG'), ('BUK', 'BUK'), ('RSD', 'RSD'), ('WST', 'WST'), ('XAG', 'XAG'), ('ETB', 'ETB'), ('LUF', 'LUF'), ('KGS', 'KGS'), ('CDF', 'CDF'), ('PGK', 'PGK'), ('SDG', 'SDG'), ('ZAL', 'ZAL'), ('LAK', 'LAK'), ('KZT', 'KZT'), ('BIF', 'BIF'), ('SEK', 'SEK'), ('COP', 'COP'), ('XCD', 'XCD'), ('BZD', 'BZD'), ('SBD', 'SBD'), ('LYD', 'LYD'), ('SKK', 'SKK'), ('KHR', 'KHR'), ('MXV', 'MXV'), ('ITL', 'ITL'), ('BAN', 'BAN'), ('TWD', 'TWD'), ('YDD', 'YDD'), ('ARS', 'ARS'), ('ISJ', 'ISJ'), ('YUD', 'YUD'), ('AON', 'AON'), ('VEF', 'VEF'), ('MRU', 'MRU'), ('CZK', 'CZK'), ('NLG', 'NLG'), ('PTE', 'PTE'), ('ERN', 'ERN'), ('IEP', 'IEP'), ('HRK', 'HRK'), ('PLZ', 'PLZ'), ('SZL', 'SZL'), ('LBP', 'LBP'), ('XBA', 'XBA'), ('MVP', 'MVP'), ('BOB', 'BOB'), ('UAH', 'UAH'), ('XDR', 'XDR'), ('ESA', 'ESA'), ('MUR', 'MUR'), ('TMM', 'TMM'), ('BGM', 'BGM'), ('HRD', 'HRD'), ('SIT', 'SIT'), ('ESB', 'ESB'), ('FJD', 'FJD'), ('XBD', 'XBD'), ('XBC', 'XBC'), ('SOS', 'SOS'), ('PAB', 'PAB'), ('HNL', 'HNL'), ('OMR', 'OMR'), ('ZRZ', 'ZRZ'), ('CHE', 'CHE'), ('ILP', 'ILP'), ('MAD', 'MAD'), ('ISK', 'ISK'), ('MVR', 'MVR'), ('JOD', 'JOD'), ('MAF', 'MAF'), ('SHP', 'SHP'), ('KYD', 'KYD'), ('BOL', 'BOL'), ('BBD', 'BBD'), ('CLE', 'CLE'), ('CRC', 'CRC'), ('GHC', 'GHC'), ('MCF', 'MCF'), ('UGX', 'UGX'), ('LSL', 'LSL'), ('BEC', 'BEC'), ('CUC', 'CUC'), ('UGS', 'UGS'), ('USS', 'USS'), ('MOP', 'MOP'), ('TRL', 'TRL'), ('DEM', 'DEM'), ('VNN', 'VNN'), ('BDT', 'BDT'), ('HKD', 'HKD'), ('XRE', 'XRE'), ('MKN', 'MKN'), ('EGP', 'EGP'), ('SVC', 'SVC'), ('TPE', 'TPE'), ('TZS', 'TZS'), ('BND', 'BND'), ('NGN', 'NGN'), ('CLP', 'CLP'), ('BRR', 'BRR'), ('MGF', 'MGF'), ('MRO', 'MRO'), ('TRY', 'TRY'), ('TND', 'TND'), ('ALK', 'ALK'), ('BWP', 'BWP'), ('ARP', 'ARP'), ('INR', 'INR'), ('AOK', 'AOK'), ('GHS', 'GHS'), ('LTL', 'LTL'), ('ZWD', 'ZWD'), ('BMD', 'BMD'), ('STN', 'STN'), ('TJS', 'TJS'), ('BHD', 'BHD'), ('LTT', 'LTT'), ('AZN', 'AZN'), ('TOP', 'TOP'), ('XPD', 'XPD'), ('TTD', 'TTD'), ('KES', 'KES'), ('GRD', 'GRD'), ('ZMW', 'ZMW'), ('CYP', 'CYP'), ('GIP', 'GIP'), ('TJR', 'TJR'), ('USN', 'USN'), ('ARL', 'ARL'), ('XPT', 'XPT'), ('GQE', 'GQE'), ('GWE', 'GWE'), ('CHW', 'CHW'), ('NIC', 'NIC'), ('AMD', 'AMD'), ('SDD', 'SDD'), ('ARA', 'ARA'), ('BGO', 'BGO'), ('ZMK', 'ZMK'), ('USD', 'USD'), ('GNS', 'GNS'), ('MMK', 'MMK'), ('BRE', 'BRE'), ('HTG', 'HTG'), ('SSP', 'SSP'), ('KWD', 'KWD'), ('BAD', 'BAD'), ('MZM', 'MZM'), ('BRN', 'BRN'), ('BTN', 'BTN'), ('MTP', 'MTP'), ('HUF', 'HUF'), ('PES', 'PES'), ('XXX', 'XXX'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('ZWL', 'ZWL'), ('AOR', 'AOR'), ('GWP', 'GWP'), ('BRC', 'BRC'), ('MGA', 'MGA'), ('PHP', 'PHP'), ('FRF', 'FRF'), ('MTL', 'MTL'), ('BYN', 'BYN'), ('RWF', 'RWF'), ('XEU', 'XEU'), ('XOF', 'XOF'), ('MKD', 'MKD'), ('GYD', 'GYD'), ('RUR', 'RUR'), ('SRG', 'SRG'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('BRZ', 'BRZ'), ('TMT', 'TMT'), ('YUM', 'YUM'), ('XAF', 'XAF'), ('CUP', 'CUP'), ('DOP', 'DOP'), ('FKP', 'FKP'), ('MXP', 'MXP'), ('UYI', 'UYI')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='withdrawl',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
